# Netlify config para SPA (sem redirect especial de /auth/*)

[build]
  command = "npm run build"
  publish = "dist"

# Regra SPA catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Opcional) headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
